# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="employee",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
