# Generated by Django 6.0.4 on 2026-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('notifications', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('REMINDER_24H', 'Reminder 24h'), ('REMINDER_1H', 'Reminder 1h')], default='BOOKING_CREATED', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('appointment', 'channel', 'event_type'), name='uq_notification_appointment_channel_event'),
        ),
    ]
