# Generated by Django 6.0.4 on 2026-04-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_error_message_notification_event_type_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to='tenants.business')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entry', to='notifications.notification')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_0a6c2d_idx')],
            },
        ),
    ]
