# Generated by Django 6.0.4 on 2026-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='provider_status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
