# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationoutbox_delivered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("TELEGRAM", "Telegram"),
                ],
                max_length=16,
            ),
        ),
    ]
